[versions]
kotlin = "1.9.20"
hoplite = "2.7.5"
jimfs = "1.3.0"

[plugins]
kotlin-jvm = { version.ref = "kotlin", id = "org.jetbrains.kotlin.jvm" }

[libraries]
hoplite-core = { version.ref = "hoplite", group = "com.sksamuel.hoplite", name = "hoplite-core" }
jimfs = { version.ref = "jimfs", group = "com.google.jimfs", name = "jimfs" }
